// Type declarations for the shared JS protocol module so the renderer gets
// literal types for METHODS/EVENTS without duplicating their definitions.

export declare const PROTOCOL_VERSION: '1.0'

export declare const METHODS: {
  readonly DEVICES_LIST: 'devices.list'
  readonly DEVICES_PAIR: 'devices.pair'
  readonly DEVICES_PAIR_CODE: 'devices.pairCode'
  readonly DEVICES_GET_CODE: 'devices.getCode'
  readonly DEVICES_RENAME: 'devices.rename'
  readonly DEVICES_REMOVE: 'devices.remove'
  readonly DEVICES_FAVORITE: 'devices.favorite'
  readonly DEVICES_TRUST: 'devices.trust'
  readonly DEVICES_GET_IDENTITY: 'devices.getIdentity'
  readonly DEVICES_SPEED_TEST: 'devices.speedTest'
  readonly PRESENCE_SET: 'presence.set'
  readonly PRESENCE_GET: 'presence.get'
  readonly DIAGNOSTICS_GET: 'diagnostics.get'
  readonly NOTIFICATIONS_LIST: 'notifications.list'
  readonly NOTIFICATIONS_CLEAR: 'notifications.clear'
  readonly NOTIFICATIONS_MARK_READ: 'notifications.markRead'
  readonly HISTORY_LIST: 'history.list'
  readonly HISTORY_CLEAR: 'history.clear'
  readonly CONNECTION_STATUS: 'connection.status'
  readonly SETTINGS_GET: 'settings.get'
  readonly SETTINGS_UPDATE: 'settings.update'
  readonly STORAGE_STATS: 'storage.stats'
  readonly STORAGE_CLEAR: 'storage.clear'
  readonly FILES_CREATE_CODE: 'files.createCode'
  readonly FILES_CLAIM_CODE: 'files.claimCode'
  readonly FILES_LIST_PENDING: 'files.listPending'
  readonly FILES_EXTEND_EXPIRATION: 'files.extendExpiration'
  readonly FILES_CANCEL_CODE: 'files.cancelCode'
  readonly FILES_DELETE_PENDING: 'files.deletePending'
  readonly TRANSFERS_START: 'transfers.start'
  readonly TRANSFERS_ACCEPT: 'transfers.accept'
  readonly TRANSFERS_DECLINE: 'transfers.decline'
  readonly TRANSFERS_PAUSE: 'transfers.pause'
  readonly TRANSFERS_RESUME: 'transfers.resume'
  readonly TRANSFERS_CANCEL: 'transfers.cancel'
  readonly TRANSFERS_RETRY: 'transfers.retry'
  readonly TRANSFERS_LIST: 'transfers.list'
  readonly TRANSFERS_CLEAR: 'transfers.clear'
  readonly TRANSFERS_DELETE: 'transfers.delete'
  readonly TRANSFERS_BROADCAST: 'transfers.broadcast'
  readonly SYNC_ADD: 'sync.add'
  readonly SYNC_REMOVE: 'sync.remove'
  readonly SYNC_LIST: 'sync.list'
  readonly SYNC_TRIGGER: 'sync.trigger'
  readonly SYNC_PAUSE: 'sync.pause'
  readonly SYNC_RESUME: 'sync.resume'
  readonly SYNC_ACCEPT_INVITE: 'sync.acceptInvite'
  readonly SYNC_DECLINE_INVITE: 'sync.declineInvite'
  readonly SYNC_LIST_INVITES: 'sync.listInvites'
  readonly SHARED_LIST: 'shared.list'
  readonly SHARED_REMOVE: 'shared.remove'
  readonly SHARED_FAVORITE: 'shared.favorite'
  readonly DRIVE_GET_STATUS: 'drive.getStatus'
  readonly DRIVE_MOUNT: 'drive.mount'
  readonly DRIVE_UNMOUNT: 'drive.unmount'
  readonly DRIVE_UPDATE_PERMISSIONS: 'drive.updatePermissions'
  readonly DRIVE_BROADCAST_FILE: 'drive.broadcastFile'
  readonly DRIVE_SHARE_INVITE: 'drive.shareInvite'
  readonly DRIVE_SHARE_ACCEPT: 'drive.shareAccept'
  readonly DRIVE_SHARE_DECLINE: 'drive.shareDecline'
  readonly CHECK_FOR_UPDATES: 'system.checkForUpdates'
  readonly CLIPBOARD_SEND: 'clipboard.send'
  readonly WATCH_STATE_BROADCAST: 'watch.stateBroadcast'
  readonly WATCH_PARTY_CREATE: 'watch.createRoom'
  readonly WATCH_PARTY_JOIN: 'watch.joinRoom'
  readonly WATCH_PARTY_LEAVE: 'watch.leaveRoom'
  readonly WATCH_PARTY_GET_ROOM: 'watch.getRoom'
  readonly WATCH_PARTY_LIST_ROOMS: 'watch.listRooms'
  readonly WATCH_PARTY_REACTION: 'watch.reaction'
  readonly WATCH_PARTY_STATUS: 'watch.status'
  readonly STREAM_URL_GET: 'stream.getUrl'
}

export declare const EVENTS: {
  readonly WATCH_ROOM_CREATED: 'watch.room_created'
  readonly WATCH_ROOM_JOINED: 'watch.room_joined'
  readonly WATCH_ROOM_LEFT: 'watch.room_left'
  readonly WATCH_ROOM_CLOSED: 'watch.room_closed'
  readonly WATCH_PEER_JOINED: 'watch.peer_joined'
  readonly WATCH_PEER_LEFT: 'watch.peer_left'
  readonly WATCH_PEER_STATUS: 'watch.peer_status'
  readonly WATCH_STATE_SYNC: 'watch.state_sync'
  readonly WATCH_REACTION: 'watch.reaction'
  readonly WATCH_ROOMS_DISCOVERED: 'watch.rooms_discovered'
  readonly DEVICE_ONLINE: 'device.online'
  readonly DEVICE_OFFLINE: 'device.offline'
  readonly DEVICE_DISCOVERED: 'device.discovered'
  readonly DEVICE_PAIRED: 'device.paired'
  readonly DEVICE_UPDATED: 'device.updated'
  readonly DEVICE_REMOVED: 'device.removed'
  readonly PRESENCE_CHANGED: 'presence.changed'
  readonly PEER_CONNECTED: 'peer.connected'
  readonly PEER_DISCONNECTED: 'peer.disconnected'
  readonly WORKER_READY: 'worker.ready'
  readonly CONNECTION_CHANGED: 'connection.changed'
  readonly STORAGE_CHANGED: 'storage.changed'
  readonly NOTIFICATION_RECEIVED: 'notification.received'
  readonly TRANSFER_OFFER_RECEIVED: 'transfer.offer_received'
  readonly TRANSFER_STARTED: 'transfer.started'
  readonly TRANSFER_PROGRESS: 'transfer.progress'
  readonly TRANSFER_COMPLETED: 'transfer.completed'
  readonly TRANSFER_FAILED: 'transfer.failed'
  readonly TRANSFER_PAUSED: 'transfer.paused'
  readonly TRANSFER_RESUMED: 'transfer.resumed'
  readonly TRANSFER_CANCELLED: 'transfer.cancelled'
  readonly TRANSFER_QUEUED: 'transfer.queued'
  readonly PENDING_SHARE_UPDATED: 'pending_share.updated'
  readonly PENDING_SHARE_EXPIRED: 'pending_share.expired'
  readonly PENDING_SHARE_CLAIMED: 'pending_share.claimed'
  readonly PENDING_SHARE_CLAIM_FAILED: 'pending_share.claimFailed'
  readonly SYNC_LIBRARY_ADDED: 'sync.library_added'
  readonly SYNC_LIBRARY_REMOVED: 'sync.library_removed'
  readonly SYNC_SCAN: 'sync.scan'
  readonly SYNC_UP_TO_DATE: 'sync.up_to_date'
  readonly SYNC_COMPLETED: 'sync.completed'
  readonly SYNC_DELETED: 'sync.deleted'
  readonly SYNC_CONFLICT: 'sync.conflict'
  readonly SYNC_ERROR: 'sync.error'
  readonly SYNC_INVITE_RECEIVED: 'sync.invite_received'
  readonly SYNC_PHASE: 'sync.phase'
  readonly CLIPBOARD_RECEIVED: 'clipboard.received'
  readonly DRIVE_INVITE_RECEIVED: 'drive.inviteReceived'
  readonly DRIVE_AUTO_MOUNT: 'drive.autoMount'
  readonly UPDATING: 'updating'
  readonly UPDATED: 'updated'
  readonly SETTINGS_UPDATED: 'settings.updated'
  readonly SPEEDTEST_PROGRESS: 'speedtest.progress'
  readonly LAN_DISCOVERY_KEY: 'lan.discoveryKey'
  readonly WATCH_STATE_CHANGED: 'watch.stateChanged'
}

export declare function isProtocolCompatible(msg: unknown): boolean
export declare function generateId(): string
export declare function createRequest(method: string, params?: unknown): string
export declare function createResponse(id: string, result?: unknown, error?: string): string
export declare function createEvent(event: string, data?: unknown): string
export declare function parseMessage(buffer: { toString(): string }): Record<string, unknown> | null
